# Use postgres/example user/password credentials
version: '3.7'

services:

  postgres:
    image: postgres:13.1
    restart: always
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #POSTGRES_DB: "aviation_db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
