version = 3.11.1
runner.dialect = scala3
align.preset = most
maxColumn = 120
newlines.source = keep
lineEndings = preserve
docstrings = JavaDoc
docstrings.wrapMaxColumn = 80
project.git = true
rewrite.rules = [RedundantBraces, RedundantParens, Imports]
rewrite.scala3.removeOptionalBraces = no
rewrite.scala3.convertToNewSyntax = false
