image: openjdk:11-buster

stages:
  - build
  - test
  - report

before_script:
  - apt-get update -y
  - apt-get install apt-transport-https -y
  - echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
  - apt-get update -y
  - apt-get install sbt
  - sbt update

compile:
  stage: build
  script:
    - sbt clean compile
  
test:
  stage: test
  script:
    - sbt test

deps:
  stage: report
  script:
    - sbt dependencyUpdates
    