image: hseeberger/scala-sbt:11.0.7_1.3.10_2.13.2

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
  COURSIER_CACHE: sbt-cache/coursier #only needed if you use coursier

cache:
  # if you want to have a separate cache per branch, uncomment the next line
  # key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - "sbt-cache/ivy/cache"
    - "sbt-cache/boot"
    - "sbt-cache/sbtboot"
    - "sbt-cache/target"
    - "sbt-cache/coursier" #only needed if you use coursier  
  
stages:
  - build
  - test
  - report

before_script:
  - java -version
  - sbt update

compile:
  stage: build
  script:
    - sbt clean compile
  
test:
  stage: test
  script:
    - sbt test

deps:
  stage: report
  script:
    - sbt dependencyUpdates
    