language: java

jdk:
  - oraclejdk8

before_install:
  - mkdir -p /home/travis/.sbt/launchers/1.2.3
  - curl http://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.2.3/sbt-launch-1.2.3.jar -o /home/travis/.sbt/launchers/1.2.3/sbt-launch.jar

script:
  - cd $TRAVIS_BUILD_DIR/webapp-api && sbt ";clean ;coverage ;assembly ;coverageReport"
  - cd $TRAVIS_BUILD_DIR && ./gradlew clean build
