language: java

jdk:
  - oraclejdk8

script:
  - cd $TRAVIS_BUILD_DIR && sbt ";clean ;coverage ;assembly ;coverageReport; coverageAggregate"
  - cd $TRAVIS_BUILD_DIR/scala-boot-neo4j && ./gradlew clean build

after_success:
  - cd $TRAVIS_BUILD_DIR && sbt coveralls