language: java

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build
  - sbt ";clean;coverage;test;coverageReport"
  - bash <(curl -s https://codecov.io/bash) -t 551ffd9e-aac2-4eff-937c-d8bcca72bf38
