language: java

jdk:
  - oraclejdk8

before_install:
  - mkdir -p /home/travis/.sbt/launchers/1.2.1
  - curl http://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.2.1/sbt-launch-1.2.1.jar -o /home/travis/.sbt/launchers/1.2.1/sbt-launch.jar

jobs:
  include:
    - stage: "Testing"
      script:
        - cd webapp-api && sbt ";clean ;test"
        - ./gradlew clean test
    - stage: "Packaging"
      script:
        - sbt package
        
#  - sbt ";clean ;coverage ;test ;coverageReport; assembly"