# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx2048m
      TERM: dumb

    steps:
      - checkout

      # compiler, test & run
      - run:
          name: clean, test
          command: |
            java -version
            sbt -mem 2048 clean test

      - run:
          name: coverage, dependencies
          command: |
            sbt -mem 2048 xcoverage
            sbt -mem 2048 xdup
            curl -Os https://uploader.codecov.io/latest/codecov-linux
            chmod +x codecov-linux
            ./codecov-linux -t ${CODECOV_TOKEN}
