name: Scala CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened ]

jobs:
  build:

    runs-on: ubuntu-24.04
    timeout-minutes: 10

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:17-alpine
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aviation_db
        ports:
          - 5432:5432  
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: compile main
      run: sbt -v -Dfile.encoding=UTF-8 --client compile
    - name: compile unit tests
      run: sbt -v -Dfile.encoding=UTF-8 --client Test/compile
    - name: compile integration tests
      #run: sbt -v -Dfile.encoding=UTF-8 --client IntegrationTest/compile
      run: echo "TODO"
    - name: tests with coverage
      run: sbt --client xcoverage
    - name: upload coverage reports to codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#    - name: tests
#      run: sbt -v -Dfile.encoding=UTF-8 --client test
    - name: integration tests
      #run: sbt -v -Dfile.encoding=UTF-8 --client "hexagonal/IntegrationTest/test"
      run: echo "TODO"
    - name: assembly
      run: sbt -v --client assembly
    - name: dependency updates report
      run: sbt -v --client dependencyUpdates
