name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11
    - name: java version
      run: java -version
    - name: compile main
      run: sbt -v -Dfile.encoding=UTF-8 --client clean compile
    - name: compile unit tests
      run: sbt -v -Dfile.encoding=UTF-8 --client test:compile
    - name: compile integration tests
      run: sbt -v -Dfile.encoding=UTF-8 --client it:compile
    - name: tests
      run: sbt -v -Dfile.encoding=UTF-8 --client test
    - name: integration tests
      run: sbt -v -Dfile.encoding=UTF-8 --client it:test
    - name: assembly
      run: sbt -v -Dfile.encoding=UTF-8 --client assembly
