name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:16-alpine
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aviation_db
        ports:
          - 5432:5432  
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Setup Scala and Java
      uses: coursier/setup-action@v1
      with:
        jvm: zulu@17
    - name: java version
      run: java -version
    - name: compile main
      run: sbt -v -Dfile.encoding=UTF-8 --client compile
    - name: compile unit tests
      run: sbt -v -Dfile.encoding=UTF-8 --client Test/compile
    - name: compile integration tests
      #run: sbt -v -Dfile.encoding=UTF-8 --client IntegrationTest/compile
      run: echo "TODO"
    - name: tests
      run: sbt -v -Dfile.encoding=UTF-8 --client test
    - name: integration tests
      #run: sbt -v -Dfile.encoding=UTF-8 --client "hexagonal/IntegrationTest/test"
      run: echo "TODO"
    - name: assembly
      run: sbt -v -Dfile.encoding=UTF-8 --client assembly
    - name: dependency updates report
      run: sbt -v -Dfile.encoding=UTF-8 --client dependencyUpdates
