@startuml
skinparam monochrome true
skinparam BoxPadding 5
header Ports and Adapter POC
title Quill Repository Architecture

interface Idiom
interface NamingStrategy
interface Context
interface AbstractRepository {
  {method} insert(e: Entity) : Id
  {method} update(e: Entity) : Int
  {method} delete(id: Long) : Int
  {method} findById(code: String) : Entity
}
interface EntityContext <I,N> {
  {method} insertQuery[T](entity: T)
  {method} updateQuery[T](entity: T)
  {method} deleteQuery[T](entity: T)
  {method} findCountryByCodeQuery(code: String)
}
class CountryRepository {
  {method} insert(country: Country): Future[Country]
  {method} update(country: Country): Future[Country]
  {method} delete(country: Country): Future[Country]
  {method} findByCode(code: String): Future[Country]
}

Context <-- EntityContext
Idiom <-- EntityContext
IOMonad <-- EntityContext
NamingStrategy <-- EntityContext

NamingStrategy <-- PostgresAsyncContext

AbstractRepository <|-- CountryRepository
EntityContext <-- CountryRepository
PostgresAsyncContext <-- CountryRepository

CountryRepository -right-> ExecutionContext

@enduml