@startuml
skinparam monochrome true
skinparam BoxPadding 5
header Ports and Adapter POC
title Quill Repository Architecture

interface Idiom
interface NamingStrategy
interface Context
interface AbstractRepository {
  {method} insert(e: Entity) : Id
  {method} update(e: Entity) : Int
  {method} delete(id: Long) : Int
  {method} findById(code: String) : Entity
}
interface ModularContext <I,N>
class     CountryRepository {
  {method} findByCode(code: String) : Country
}

Context <-- ModularContext
Idiom <-- ModularContext
NamingStrategy <-- ModularContext

NamingStrategy <-- PostgresAsyncContext

AbstractRepository <|-- CountryRepository
ModularContext <-- CountryRepository
PostgresAsyncContext <-- CountryRepository

CountryRepository -right-> ExecutionContext

@enduml